export const ADD_SERIES = "ADD_SERIES";
export const GET_SERIES = "GET_SERIES";
export const SELECT_SERIES = "SELECT_SERIES";
export const SELECT_EPISODE = "SELECT_EPISODE";
export const ADD_EPISODE = "ADD_EPISODE";
export const GET_EPISODES = "GET_EPISODES";
export const UPLOADED_SUCCESSFULLY = "UPLOADED_SUCCESSFULLY";
export const WRONG_UPLOAD = "WRONG_UPLOAD";
export const RESET_REQUEST_STATES = "RESET_REQUEST_STATES";

export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAIL = "DELETE_FAIL";


export const AUTH_START = "AUTH_START";
export const AUTH_ADMIN_SUCCESS = "AUTH_ADMIN_SUCCESS";
export const AUTH_ADMIN_FAIL = "AUTH_ADMIN_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_RENDER_ADMIN = "AUTH_RENDER_ADMIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";
