export const ADD_SERIES = "ADD_SERIES";
export const GET_SERIES = "GET_SERIES";
export const SELECT_SERIES = "SELECT_SERIES";

export const SELECT_EPISODE = "SELECT_EPISODE";
export const ADD_EPISODE = "ADD_EPISODE";
export const GET_EPISODE = "GET_EPISODE";

export const UPLOADED_SUCCESSFULLY = "UPLOADED_SUCCESSFULLY";
export const WRONG_UPLOAD = "WRONG_UPLOAD";
export const RESET_UPLOAD_STATE = "RESET_UPLOAD_STATE";



